name: test
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  equatable: ^2.0.7
  uuid: ^4.5.1
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  intl: ^0.19.0
  shared_preferences: ^2.5.2
  easy_localization: ^3.0.7+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.4.0
  get_it: ^8.0.3
  flutter_local_notifications: ^18.0.0
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0  
  flutter_datetime_picker_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    # - assets/images/