// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGhDH3WKx627xU1_-jYe481GDszXxoJ30',
    appId: '1:844875239439:web:53a0247e6de081fcb1d37a',
    messagingSenderId: '844875239439',
    projectId: 'todo-flutter-app-ai',
    authDomain: 'todo-flutter-app-ai.firebaseapp.com',
    storageBucket: 'todo-flutter-app-ai.firebasestorage.app',
    measurementId: 'G-P4NS10R42G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArlqpktmsKW1yoFPu0MRkORtjOuOkDMwI',
    appId: '1:844875239439:android:dcc1b73630236ddcb1d37a',
    messagingSenderId: '844875239439',
    projectId: 'todo-flutter-app-ai',
    storageBucket: 'todo-flutter-app-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkfWx47UDeevp5HJjqRTweh8oFgyuvJOU',
    appId: '1:844875239439:ios:2044b0fcbe4b02ceb1d37a',
    messagingSenderId: '844875239439',
    projectId: 'todo-flutter-app-ai',
    storageBucket: 'todo-flutter-app-ai.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkfWx47UDeevp5HJjqRTweh8oFgyuvJOU',
    appId: '1:844875239439:ios:2044b0fcbe4b02ceb1d37a',
    messagingSenderId: '844875239439',
    projectId: 'todo-flutter-app-ai',
    storageBucket: 'todo-flutter-app-ai.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGhDH3WKx627xU1_-jYe481GDszXxoJ30',
    appId: '1:844875239439:web:0416477244f7924db1d37a',
    messagingSenderId: '844875239439',
    projectId: 'todo-flutter-app-ai',
    authDomain: 'todo-flutter-app-ai.firebaseapp.com',
    storageBucket: 'todo-flutter-app-ai.firebasestorage.app',
    measurementId: 'G-L89JC10GVS',
  );
}
